import React from 'react';
import './AboutUsPopup.css'
import {useTranslation} from "react-i18next";

const AboutUsPopup = ({setAbout}) => {

    const { t } = useTranslation()


    return (
        <div className="returnPolicy2" onClick={()=>setAbout(false)}>
            <div className="returnBlock2">
                <img className="closeGuide" src="https://i.pinimg.com/originals/52/e3/86/52e38681b082f94f2917624bb56edf42.png" alt="" onClick={() => setAbout(false)}/>
                <div className="title col-md-12 col-lg-10">
                    <h3 className="mbr-section-title mbr-fonts-style align-center mb-4 display-2 "><strong>{t("private:text1")}</strong>
                        <div><strong><br/></strong></div>
                    </h3>
                    <h4 className="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-5">{t("private:text2")}
                        <div><br/></div>
                        <div>{t("private:text3")}</div>
                        <div><br/></div>
                        <div>{t("private:text4")}</div>
                        <div><br/></div>
                        <div>{t("private:text5")}</div>
                        <div><br/></div>
                        <div>{t("private:text6")}</div>
                        <div>{t("private:text8")}</div>
                        <div>{t("private:text9")}</div>
                        <div>{t("private:text10")}</div>
                        <div>{t("private:text11")}</div>
                        <div>{t("private:text12")}</div>
                        <div>{t("private:text13")}</div>
                        <div>{t("private:text14")}</div>
                        <div>{t("private:text15")}</div>
                        <div>{t("private:text16")}</div>
                        <div>{t("private:text17")}</div>
                        <div>{t("private:text18")}</div>
                        <div>{t("private:text19")}</div>
                        <div>{t("private:text20")}</div>
                        <div>{t("private:text21")}</div>
                        <div>{t("private:text22")}</div>
                        <div>{t("private:text23")}</div>
                        <div><br/></div>
                        <div>{t("private:text24")}</div>
                        <div>{t("private:text25")}</div>
                        <div>{t("private:text26")}</div>
                        <div><br/></div>
                        <div>{t("private:text27")}</div>
                        <div>{t("private:text28")}</div>
                        <div>{t("private:text29")}</div>
                        <div>{t("private:text30")}</div>
                        <div>{t("private:text31")}</div>
                        <div>{t("private:text32")}</div>
                        <div>{t("private:text33")}</div>
                        <div><br/></div>
                        <div>{t("private:text34")}</div>
                        <div>{t("private:text35")}</div>
                        <div><br/></div>
                        <div>{t("private:text36")}</div>
                        <div><br/></div>
                        <div>{t("private:text37")}</div>
                        <div><br/></div>
                        <div>{t("private:text38")}</div>
                        <div><br/></div>
                        <div>{t("private:text39")}</div>
                        <div>{t("private:text40")}</div>
                        <div>{t("private:text41")}</div>
                        <div><br/></div>
                        <div><br/></div>
                        <div>{t("private:text42")}</div>
                        <div>{t("private:text43")}</div>
                        <div><br/></div>
                        <div>{t("private:text44")}</div>
                        <div>{t("private:text45")}</div>
                        <div>{t("private:text46")}</div>
                        <div>{t("private:text47")}</div>
                        <div>{t("private:text48")}</div>
                        <div>{t("private:text49")}</div>
                        <div>{t("private:text50")}</div>
                        <div><br/></div>
                        <div><br/></div>
                        <div>{t("private:text87")}</div>
                        <div>{t("private:text88")}</div>
                        <div><br/></div>
                        <div>{t("private:text89")}</div>
                        <div><br/></div>
                        <div>{t("private:text90")}</div>
                        <div>{t("private:text91")}</div>
                        <div>{t("private:text92")}</div>
                        <div>{t("private:text93")}</div>
                        <div>{t("private:text94")}</div>
                        <div><br/></div>
                        <div><br/></div>
                        <div>{t("private:text95")}</div>
                        <div>{t("private:text96")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text97")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text51")}</div>
                        <div>{t("private:text52")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text53")}</div>
                        <div><br/></div>
                        <div>{t("private:text54")}</div>
                        <div><br/></div>
                        <div>{t("private:text55")}</div>
                        <div><br/></div>
                        <div>{t("private:text56")}</div>
                        <div>{t("private:text98")}</div>
                        <div>{t("private:text99")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text100")}</div>
                        <div>{t("private:text999")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text57")}</div>
                        <div>{t("private:text58")}</div>
                        <div><br/></div>
                        <div>{t("private:text59")}</div>
                        <div>{t("private:text60")}</div>
                        <div>{t("private:text61")}</div>
                        <div>{t("private:text62")}</div>
                        <div>{t("private:text63")}</div>
                        <div><br/></div>
                        <div><br/></div>
                        <div>{t("private:text64")}</div>
                        <div>{t("private:text65")}</div>
                        <div><br/></div>
                        <div>{t("private:text101")}</div>
                        <div>{t("private:text102")}</div>
                        <div><br/></div>
                        <div>{t("private:text103")}</div>
                        <div><br/></div>
                        <div>{t("private:text104")}</div>
                        <div><br/></div>
                        <div>{t("private:text105")}</div>
                        <div>{t("private:text106")}</div>
                        <div>{t("private:text107")}</div>
                        <div>{t("private:text108")}
                        </div>
                        <div>{t("private:text109")}</div>
                        <div>{t("private:text110")}</div>
                        <div>{t("private:text111")}</div>
                        <div>{t("private:text112")}</div>
                        <div>{t("private:text113")}</div>
                        <div>{t("private:text114")}</div>
                        <div>{t("private:text115")}</div>
                        <div>{t("private:text116")}</div>
                        <div>{t("private:text117")}</div>
                        <div><br/></div>
                        <div>{t("private:text118")}</div>
                        <div><br/></div>
                        <div>{t("private:text66")}</div>
                        <div>{t("private:text67")}</div>
                        <div><br/></div>
                        <div>{t("private:text68")}</div>
                        <div><br/></div>
                        <div>{t("private:text69")}</div>
                        <div>{t("private:text70")}</div>
                        <div><br/></div>
                        <div>{t("private:text71")}</div>
                        <div>{t("private:text72")}</div>
                        <div>{t("private:text73")}</div>
                        <div>{t("private:text74")}</div>
                        <div>{t("private:text119")}</div>
                        <div>{t("private:text120")}</div>
                        <div><br/></div>
                        <div>{t("private:text121")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text75")}</div>
                        <div>{t("private:text76")}</div>
                        <div><br/></div>
                        <div>{t("private:text77")}</div>
                        <div><br/></div>
                        <div>{t("private:text78")}</div>
                        <div>{t("private:text79")}</div>
                        <div><br/></div>
                        <div>{t("private:text80")}</div>
                        <div><br/></div>
                        <div>{t("private:text123")}</div>
                        <div>{t("private:text123")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text125")}</div>
                        <div>{t("private:text126")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text81")}</div>
                        <div>{t("private:text82")}
                        </div>
                        <div><br/></div>
                        <div>{t("private:text83")}</div>
                        <div><br/></div>
                        <div>{t("private:text84")}</div>
                        <div><br/></div>
                        <div>{t("private:text85")}</div>
                        <div>{t("private:text86")}</div>
                    </h4>
                </div>
            </div>
        </div>
    );
};

export default AboutUsPopup;